version: '3.8'

services:
  hakopostgre:
    image: postgres:latest
    restart: always
    hostname: hakopostgre
    ports:
      - "5454:5432"
    environment: 
      POSTGRES_HOST: hakopostgre
      POSTGRES_DB: hakodb
      POSTGRES_PASSWORD: hako.test
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hakodb"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - hako

  django:
    build:
      context: ./
    restart: always
    ports:
      - "8000:3000"
    depends_on: 
      hakopostgre:
        condition: service_healthy
    links:
      - hakopostgre:hakopostgre
    environment:
      DATABASE: postgres
      SQL_HOST: hakopostgre
      SQL_PORT: 5432
      SQL_DATABASE: hakodb
      SQL_USER: postgres
      SQL_PASSWORD: hako.test
    networks:
      - hako

networks:
  hako:
    driver: bridge
