# Generated by Django 4.2.11 on 2024-05-05 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Endüstri Adı')),
                ('image', models.ImageField(blank=True, upload_to='industry_images', verbose_name='Endüstri Resmi')),
                ('icon_class', models.CharField(help_text="FontAwesome ikon sınıfı, örn: 'fas fa-industry'", max_length=50, verbose_name='Endüstri İkon Sınıfı')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('subdescription', models.CharField(blank=True, max_length=255, verbose_name='Alt Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Endüstri',
                'verbose_name_plural': 'Endüstriler',
            },
        ),
    ]
